#!/bin/bash -
#===============================================================================
#
#          FILE: pkg
#
#   DESCRIPTION: Universal package manager command line
#                Support for Solus Linux eopkg package manager
#
#        AUTHOR: Bert van der Lingen 
#       CREATED: 12/22/2019
#
#      	  NOTES:
#                see also: https://getsol.us/articles/package-management/basics/en/
#
#===============================================================================

VERSION=0.1

USAGE=$(cat <<ENDSTR
Usage: ${0/\.\//} <command> [arguments]
Commands:
	install
		Install a package(s) by name
	remove
		Remove a package(s) by name
	search
		search for package(s) by name
	update
		Update local catalog then Upgrade Packages ->
		Upgrades installed packages which have a newer version
	locate FILE
		Find the package which provides FILE
	info
		Print information about a package
	list
		list the files installed with a package
	version
		version of a package(s) by name
ENDSTR
)

[ $# = 0 ] && echo "${USAGE}" && exit 1

sudo=$(which sudo|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

command="$1"
shift
case "$command" in
    help|--help)
        echo  "${USAGE}"
        ;;
#...........................................
	install)
                $sudo eopkg it "$@"
		;;
	remove)
                $sudo eopkg rm  "$@"
		;;
        update|upgrade)
#                $sudo eopkg ur # extra step not needed
                $sudo eopkg up
		;;
	search)
		eopkg sr  "$@"
		;;
	# not sure about this yet, testing
  #locate|belong)
  #              for i in $(whereis $1|cut -d ':' -f 2); do if [ ! -z $(echo $i|grep -v .gz|grep -v man) ];then  dpkg -S $i 2> /dev/null; fi;  done
		;;
	info)
		eopkg nifo "$@"
		;;
	list|files)
		eopkg search-file "$@"
		;;
    version)
		eopkg blame "$@" # | grep Installed
        ;;
#...........................................
*)
	echo Unknown command: "$1"
	echo "$USAGE"
	exit 1
	;;
esac
