#!/bin/bash -
#===============================================================================
#
#          FILE: pkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#
#===============================================================================

VERSION=0.3

USAGE=$(cat <<ENDSTR

Usage: ${0/\.\//} <command> [arguments]

Commands:

	install
		Install a package(s) by name

	remove
		Remove a package(s) by name

	search
		search for package(s) by name

	update
		Check for updates & upgrade. equivalent to update+upgrade
		Update catalog then Upgrade Packages - Install packages which have an older version already installed

	locate or belong
		Query the package which provides FILE

	info
		print information about a package - print description of a package
		
	list or files 
		list the files installed with a package

	version
		version of that tool and the underlying package manager


ENDSTR
)

[ $# = 0 ] && echo "${USAGE}" && exit 1

sudo=$(which sudo|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

command="$1"
shift
case "$command" in
    version)
        echo $VERSION
        ;;
    help|--help)
        echo  "${USAGE}"
        ;;
#...........................................
	install)
		$sudo dnf install "$@"
		;;
	remove)
		$sudo dnf remove  "$@"
		;;
	update)
		$sudo dnf upgrade
		;;
	search)
		dnf search "$@"
		;;
	locate|belong)
		for i in $(whereis $1|cut -d ':' -f 2); do if [ ! -z $(echo $i|grep -v .gz|grep -v man) ];then   dnf provides $i 2> /dev/null; fi;  done
		;;
	info)
		echo "not supported ?"
		;;	
	list|files)
		rpm -ql "$@"
		;;
#...........................................
*)
	echo Unknown command: "$1"
	echo "$USAGE"
	exit 1
	;;
esac


