#!/bin/bash -
#===============================================================================
#
#          FILE: pkg
#
#   DESCRIPTION: Universal package manager command line
#                Support for Solus Linux $cmd package manager
#
#        AUTHOR: Bert van der Lingen 
#       CREATED: 12/22/2019
#
#      	  NOTES:
#                see also: https://getsol.us/articles/package-management/basics/en/
#                This script is designed to be standalone.
#                This script is designed to be renamed the way you like.
#
#===============================================================================

VERSION=0.7

USAGE=$(eval "cat <<EOF
$(<./help)
EOF
")

sudo=$(which sudo 2> /dev/null|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

cmd="eopkg"

command="$1"
shift
case "$command" in
    help|--help)
        	echo $VERSION
        echo  "${USAGE}"
        ;;
#...........................................
	install)
        $sudo $cmd it "$@"
		;;
	remove)
        $sudo $cmd rm  "$@"
		;;
    update|upgrade)
        $sudo $cmd ur
        $sudo $cmd up
		;;
	search)
		$cmd sr  "$@"
		;;
	# not sure about this yet, testing
  	locate|belong)
  		$cmd search-file "$@"
		;;
	info)
		$cmd info "$@"
		;;
	list|files)
		$cmd search-file "$@"
		;;
    version)
		$cmd blame "$@" # | grep Installed
        ;;
	manager)
		echo $cmd
		;;
#...........................................
	*)
		[ -z $command ] || echo Unknown command: $command
		echo "$USAGE"
		;;
esac
