#!/bin/bash -
#===============================================================================
#
#          FILE: pkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#
#===============================================================================

VERSION=0.3

USAGE=$(cat <<ENDSTR

Usage: ${0/\.\//} <command> [arguments]

Commands:

	install
		Install a package(s) by name

	remove
		Remove a package(s) by name

	search
		search for package(s) by name

	update
		Update local catalog then Upgrade Packages ->
		Upgrades installed packages which have a newer version 

	locate FILE
		Find the package which provides FILE

	info
		Print information about a package
		
	list 
		list the files installed with a package

	version
		version of that tool and the underlying package manager


ENDSTR
)

[ $# = 0 ] && echo "${USAGE}" && exit 1

sudo=$(which sudo|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

command="$1"
shift
case "$command" in
    version)
        echo $VERSION
        ;;
    help|--help)
        echo  "${USAGE}"
        ;;
#...........................................
	install)
		$sudo zypper install "$@"
		;;
	remove)
		$sudo zypper remove  "$@"
		;;
        update|upgrade)
		$sudo zypper update 
		;;
	search)
		zypper search "$@"
		;;
	locate|belong)
		for i in $(whereis $1|cut -d ':' -f 2); do if [ ! -z $(echo $i|grep -v .gz|grep -v man) ];then   zypper info $i 2> /dev/null; fi;  done
		;;
	info)
		zypper service-list "$@"
		;;	
	list|files)
		rpm -Ql "$@"
		;;			
#...........................................
*)
	echo Unknown command: "$1"
	echo "$USAGE"
	exit 1
	;;
esac


