#!/bin/bash -
#===============================================================================
#
#          FILE: pkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#
#===============================================================================

VERSION=0.4

USAGE=$(cat <<ENDSTR

Usage: ${0/\.\//} <command> [arguments]

Commands:

	install
		Install a package(s) by name

	remove
		Remove a package(s) by name

	search
		search for package(s) by name

	update
		Update local catalog then Upgrade Packages ->
		Upgrades installed packages which have a newer version 

	locate FILE
		Find the package which provides FILE

	info
		Print information about a package
		
	list 
		list the files installed with a package

	version
		version of a package(s) by name


ENDSTR
)

[ $# = 0 ] && echo "${USAGE}" && exit 1

sudo=$(which sudo|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

command="$1"
shift
case "$command" in
    help|--help)
        echo  "${USAGE}"
        ;;
#...........................................
	install)
		$sudo tazpkg get-install "$@"
		;;
	remove)
		$sudo tazpkg remove  "$@"
		;;
        update|upgrade)
		$sudo tazpkg upgrade
		;;
	search)
		tazpkg search "$@"
		;;
	locate|belong)
		tazpkg search-file "$@"
		;;
	info)
		tazpkg info "$@"
		;;	
	list|files)
		tazpkg list-files "$@"
		;;
    version)
		tazpkg info "$@" | grep Version
		;;			
#...........................................
*)
	echo Unknown command: "$1"
	echo "$USAGE"
	exit 1
	;;
esac


