#!/bin/bash -
#===============================================================================
#
#          FILE: upkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#                This script is designed to be standalone.
#                This script is designed to be renamed the way you like.
#
#===============================================================================

VERSION=0.7

USAGE=$(eval "cat <<EOF
$(<./help)
EOF
")

sudo=$(which sudo 2> /dev/null|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

cmd="pacman"

command="$1"
shift
case "$command" in

	help|--help)
        	echo $VERSION
		echo "$USAGE"
		;;

#...........................................
	install)
		$sudo $cmd -S --needed "$@"
		;;
	remove)
		$sudo $cmd -Rsn "$@"
		;;
        update|upgrade)
		$sudo $cmd -Syyu
		;;
	search)
		$cmd -Ss  "$@"
		;;
	locate|belong)
		for i in $(whereis $1|cut -d ':' -f 2); do if [ ! -z $(echo $i|grep -v .gz|grep -v man) ];then $cmd -Qo $i  2> /dev/null; fi; done
		;;
	info)
		$cmd -Si "$@"
		;;
	list|files)
		$cmd -Ql "$@"
		;;
	version)
		$cmd -Qi "$@"| grep -e Version -e Name
		#$cmd -Qi "$@"|grep "Version\|Name"
		;;
	manager)
		echo $cmd
		;;
#...........................................
	*)
		[ -z $command ] || echo Unknown command: $command
		echo "$USAGE"
		;;
esac


