#!/bin/bash -
#===============================================================================
#
#          FILE: upkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#                This script is designed to be standalone.
#                This script is designed to be renamed the way you like.
#
#===============================================================================

VERSION=0.7

USAGE=$(eval "cat <<EOF
$(<./help)
EOF
")

sudo=$(which sudo 2> /dev/null|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

cmd="brew"

command="$1"
shift
case "$command" in

	help|--help)
        	echo $VERSION
		echo "$USAGE"
		;;

#...........................................
	install)
		$sudo $cmd install "$@"
		;;
	remove)
		$sudo $cmd uninstall  "$@"
		;;
    update|upgrade)
		$sudo $cmd upgrade
		;;
	search)
		$cmd search "$@"
		;;
	locate|belong)
		echo "not supported for now"
		;;
	info)
		$cmd desc "$@"
		;;
	list|files)
		echo "not supported for now"
		;;
	manager)
		echo $cmd
		;;
#...........................................
	*)
		[ -z $command ] || echo Unknown command: $command
		echo "$USAGE"
		;;
esac


