#!/bin/bash -
#===============================================================================
#
#          FILE: upkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#                This script is designed to be standalone.
#                This script is designed to be renamed the way you like.
#
#===============================================================================

VERSION=0.7

USAGE=$(eval "cat <<EOF
$(<./help)
EOF
")

sudo=$(which sudo 2> /dev/null|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

cmd="apt-get"

command="$1"
shift
case "$command" in

	help|--help)
        	echo $VERSION
		echo "$USAGE"
		;;

#...........................................
	install)
                $sudo $cmd install "$@"
		;;
	remove)
                $sudo $cmd remove  "$@"
		;;
    update|upgrade)
            $sudo $cmd update
            $sudo $cmd -u upgrade
		;;
	search)
		apt-cache search  "$@"
		;;
	locate|belong)
                for i in $(whereis $1|cut -d ':' -f 2); do if [ ! -z $(echo $i|grep -v .gz|grep -v man) ];then  dpkg -S $i 2> /dev/null; fi;  done
		;;
	info)
		apt-cache policy "$@"
		;;
	list|files)
		dpkg -L "$@"
		;;
    version)
		apt-cache policy "$@" | grep Installed
		;;
	manager)
		echo $cmd
        ;;
#...........................................
	*)
		[ -z $command ] || echo Unknown command: $command
		echo "$USAGE"
		;;
esac


