#!/bin/bash -
#===============================================================================
#
#          FILE: upkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#                This script is designed to be standalone.
#                This script is designed to be renamed the way you like.
#
#===============================================================================

VERSION=0.6

USAGE=$(cat <<ENDSTR

Usage: ${0/\.\//} <command> [arguments]

Commands:

	install
		Install a package(s) by name

	remove
		Remove a package(s) by name

	search
		Search for package(s) by name

	update
		Update local catalog then Upgrade Packages ->
		Upgrades installed packages which have a newer version

	locate FILE
		Find the package which provides FILE

	info
		Print information about a package

	list
		List the files installed with a package

	version
		Gives the version number of a package(s) by name
		
-		
ENDSTR
)

sudo=$(which sudo 2> /dev/null|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

command="$1"
shift
case "$command" in

	help|--help)
        	echo $VERSION
		echo "$USAGE"
		;;

#...........................................
	install)
		$sudo brew install "$@"
		;;
	remove)
		$sudo brew uninstall  "$@"
		;;
        update|upgrade)
		$sudo brew upgrade
		;;
	search)
		brew search "$@"
		;;
	locate|belong)
		echo "not supported for now"
		;;
	info)
		brew desc "$@"
		;;
	list|files)
		echo "not supported for now"
		;;
#...........................................
	*)
		[ -z $command ] || echo Unknown command: $command
		echo "$USAGE"
		;;
esac


