#!/bin/bash -
#===============================================================================
#
#          FILE: upkg
#
#   DESCRIPTION: Universal package manager command line
#
#        AUTHOR: Nadir Boussoukaia
#       CREATED: 04/04/2019
#
#      	  NOTES:
#                see also: https://wiki.archlinux.org/index.php/Pacman/Rosetta
#                This script is designed to be standalone.
#                This script is designed to be renamed the way you like.
#
#===============================================================================

VERSION=0.7

USAGE=$(eval "cat <<EOF
$(<./help)
EOF
")

sudo=$(which sudo 2> /dev/null|cut -d ':' -f 2)
if [ $(id -u) -eq 0 ]; then sudo=""; fi

cmd="xbps-"

command="$1"
shift
case "$command" in

	help|--help)
        	echo $VERSION
		echo "$USAGE"
		;;

#...........................................
	install)
		$sudo xbps-install -S "$@"
		;;
	remove)
		$sudo xbps-remove   "$@"
		;;
    update|upgrade)
		$sudo xbps-install -Su
		;;
	search)
		xbps-query -Rs "$@"
		;;
	locate|belong)
		for i in $(whereis $1|cut -d ':' -f 2); do if [ ! -z $(echo $i|grep -v .gz|grep -v man) ];then xbps-query -o  $i 2> /dev/null; fi;  done
		;;
	info)
		xbps-query -R "$@"
		;;
	list|files)
		xbps-query -R -f  "$@"
		;;
    version)
        xbps-query -R "$@" |grep "pkgver"
        ;;
	manager)
		echo $cmd
		;;
#...........................................
	*)
		[ -z $command ] || echo Unknown command: $command
		echo "$USAGE"
		;;
esac


